// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plqpnuzctypczictzrbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscXBudXpjdHlwY3ppY3R6cmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTg4MTUsImV4cCI6MjA2MjgzNDgxNX0.35eo7487xQkNXqIqLB43Id5WO3K8HY9a1FKbVitYsLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);